In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import plotly.offline as py 
py.init_notebook_mode(connected=True)                  
import plotly.graph_objs as go                         
import plotly.tools as tls                             
from collections import Counter                        
import plotly.figure_factory as ff

from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

In [2]:
df = pd.read_csv("../input/amazon-alexa-reviews/amazon_alexa.tsv", sep="\t")

In [3]:
df.head()

rating       date         variation  \
0       5  31-Jul-18  Charcoal Fabric    
1       5  31-Jul-18  Charcoal Fabric    
2       4  31-Jul-18    Walnut Finish    
3       5  31-Jul-18  Charcoal Fabric    
4       5  31-Jul-18  Charcoal Fabric    

                                    verified_reviews  feedback  
0                                      Love my Echo!         1  
1                                          Loved it!         1  
2  Sometimes while playing a game, you can answer...         1  
3  I have had a lot of fun with this thing. My 4 ...         1  
4                                              Music         1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   rating            3150 non-null   int64 
 1   date              3150 non-null   object
 2   variation         3150 non-null   object
 3   verified_reviews  3150 non-null   object
 4   feedback          3150 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 123.2+ KB


In [5]:
# HOW MANY ALEXA PRODUCTS ARE THERE?
df['variation'].nunique()

16

In [6]:
# HOW MANY COMMENTS HAVE BEEN MADE ABOUT WHICH PRODUCT? 
df['variation'].value_counts()

Black  Dot                      516
Charcoal Fabric                 430
Configuration: Fire TV Stick    350
Black  Plus                     270
Black  Show                     265
Black                           261
Black  Spot                     241
White  Dot                      184
Heather Gray Fabric             157
White  Spot                     109
White                            91
Sandstone Fabric                 90
White  Show                      85
White  Plus                      78
Oak Finish                       14
Walnut Finish                     9
Name: variation, dtype: int64

In [7]:
# WHICH ALEXA PRODUCT GETS THE HIGHEST VOTES? 
df.groupby('variation').agg({"rating":"mean"}).sort_values('rating', ascending = False).head()

rating
variation                             
Walnut Finish                 4.888889
Oak Finish                    4.857143
Charcoal Fabric               4.730233
Heather Gray Fabric           4.694268
Configuration: Fire TV Stick  4.591429

In [8]:
# HOW MANY POSITIVE FEEDBACKS ARE THERE? 
# 1 = Positive , 0 = negative
df["feedback"].value_counts()

1    2893
0     257
Name: feedback, dtype: int64

In [9]:
trace0 = go.Bar(
            x = df[df["feedback"]== 1]["feedback"].value_counts().index.values,
            y = df[df["feedback"]== 1]["feedback"].value_counts().values,
            name='Positive Feedback')

trace1 = go.Bar(
            x = df[df["feedback"]== 0]["feedback"].value_counts().index.values,
            y = df[df["feedback"]== 0]["feedback"].value_counts().values,
            name='Negative Feedback')


data = [trace0, trace1]
layout = go.Layout(yaxis=dict(title='Count'),
                   xaxis=dict(title='Feedback'),title='Feedback Distribution')

fig = go.Figure(data=data, layout=layout)
fig.data[0].marker.line.width = 4
fig.data[0].marker.line.color = "black"
fig.data[1].marker.line.width = 4
fig.data[1].marker.line.color = "black"
py.iplot(fig)

In [10]:
# HOW MANY POSITIVE AND NEGATIVE COMMENTS WERE WRITTEN ON WHICH PRODUCT? 
trace0 = go.Bar(
            x = df[df["feedback"]== 1]["variation"].value_counts().index.values,
            y = df[df["feedback"]== 1]["variation"].value_counts().values,
            name='Positive Feedback')

trace1 = go.Bar(
            x = df[df["feedback"]== 0]["variation"].value_counts().index.values,
            y = df[df["feedback"]== 0]["variation"].value_counts().values,
            name='Negative Feedback')

data = [trace0, trace1]
layout = go.Layout(yaxis=dict(title='Count'),
                   xaxis=dict(title='Feedback'),title='Feedback distribution')

fig = go.Figure(data=data, layout=layout)
fig.data[0].marker.line.width = 4
fig.data[0].marker.line.color = "black"
fig.data[1].marker.line.width = 4
fig.data[1].marker.line.color = "black"
py.iplot(fig)

In [11]:
# AVERAGE VOTES OF THE PRODUCTS 
rating = df.groupby('variation').agg({"rating":"mean"})
rating['variation'] = rating.index
rating.reset_index(drop=True)

trace = go.Bar(x=rating['variation'], y=rating['rating'])

layout = go.Layout(yaxis=dict(title='Average Rating'),
                   xaxis=dict(title='Alexa Product'),title='Product - Avarage Rating Distribution')

fig = go.Figure(data=trace, layout=layout)
fig.data[0].marker.line.width = 2
fig.data[0].marker.line.color = "black"
py.iplot(fig)

In [12]:
# HOW MUCH WAS USED FROM WHICH VOTES?
trace = go.Bar(
            x = df["rating"].value_counts().index.values,
            y = df["rating"].value_counts().values,
            name='Quantity')

layout = go.Layout(yaxis=dict(title='Quantity'),
                   xaxis=dict(title='Ratings'),title='# of Votes Quantity')

fig = go.Figure(data=trace, layout=layout)
fig.data[0].marker.line.width = 2
fig.data[0].marker.line.color = "black"
py.iplot(fig)

<a id='2'></a><center> <h1 style="background-color:orange; color:white" ><br>Data Cleaning and Feature Engineering<br></h1>

In [13]:
#The date and rating of users' comments have been removed. 
#The date on which the comment is made does not matter about the comment. 
#It may cause overfitting as the given score will be directly proportional to the comment. 
#Therefore, the date and rating columns have been removed. 
df = df.drop(['date','rating'], axis=1)
df.head()

variation                                   verified_reviews  \
0  Charcoal Fabric                                       Love my Echo!   
1  Charcoal Fabric                                           Loved it!   
2    Walnut Finish   Sometimes while playing a game, you can answer...   
3  Charcoal Fabric   I have had a lot of fun with this thing. My 4 ...   
4  Charcoal Fabric                                               Music   

   feedback  
0         1  
1         1  
2         1  
3         1  
4         1

In [14]:
# Each of the products has been adjusted for the random forest.
variation_dummies = pd.get_dummies(df['variation'], drop_first = True)
variation_dummies.head()

Black  Dot  Black  Plus  Black  Show  Black  Spot  Charcoal Fabric   \
0           0            0            0            0                 1   
1           0            0            0            0                 1   
2           0            0            0            0                 0   
3           0            0            0            0                 1   
4           0            0            0            0                 1   

   Configuration: Fire TV Stick  Heather Gray Fabric   Oak Finish   \
0                             0                     0            0   
1                             0                     0            0   
2                             0                     0            0   
3                             0                     0            0   
4                             0                     0            0   

   Sandstone Fabric   Walnut Finish   White  White  Dot  White  Plus  \
0                  0               0      0           0            0   
1                  0               0      0           0            0   
2                  0               1      0           0            0   
3                  0               0      0           0            0   
4                  0               0      0           0            0   

   White  Show  White  Spot  
0            0            0  
1            0            0  
2            0            0  
3            0            0  
4            0            0

In [15]:
df.drop(['variation'], axis=1, inplace=True)
df.head()

verified_reviews  feedback
0                                      Love my Echo!         1
1                                          Loved it!         1
2  Sometimes while playing a game, you can answer...         1
3  I have had a lot of fun with this thing. My 4 ...         1
4                                              Music         1

In [16]:
df = pd.concat([df, variation_dummies], axis=1)
df.head()

verified_reviews  feedback  Black  Dot  \
0                                      Love my Echo!         1           0   
1                                          Loved it!         1           0   
2  Sometimes while playing a game, you can answer...         1           0   
3  I have had a lot of fun with this thing. My 4 ...         1           0   
4                                              Music         1           0   

   Black  Plus  Black  Show  Black  Spot  Charcoal Fabric   \
0            0            0            0                 1   
1            0            0            0                 1   
2            0            0            0                 0   
3            0            0            0                 1   
4            0            0            0                 1   

   Configuration: Fire TV Stick  Heather Gray Fabric   Oak Finish   \
0                             0                     0            0   
1                             0                     0            0   
2                             0                     0            0   
3                             0                     0            0   
4                             0                     0            0   

   Sandstone Fabric   Walnut Finish   White  White  Dot  White  Plus  \
0                  0               0      0           0            0   
1                  0               0      0           0            0   
2                  0               1      0           0            0   
3                  0               0      0           0            0   
4                  0               0      0           0            0   

   White  Show  White  Spot  
0            0            0  
1            0            0  
2            0            0  
3            0            0  
4            0            0

In [17]:
# All of the comments have been vectorized. 
# In this way, it was made meaningful for the random forest algorithm. 
# Each word in the data set was expressed as a number. 
# NLP techniques were not applied in detail in this study. 

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(df['verified_reviews'])
alexa_countvectorizer = vectorizer.fit_transform(df['verified_reviews'])


In [18]:
print(alexa_countvectorizer.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
df.drop(['verified_reviews'], axis=1, inplace = True)
df.head()

feedback  Black  Dot  Black  Plus  Black  Show  Black  Spot  \
0         1           0            0            0            0   
1         1           0            0            0            0   
2         1           0            0            0            0   
3         1           0            0            0            0   
4         1           0            0            0            0   

   Charcoal Fabric   Configuration: Fire TV Stick  Heather Gray Fabric   \
0                 1                             0                     0   
1                 1                             0                     0   
2                 0                             0                     0   
3                 1                             0                     0   
4                 1                             0                     0   

   Oak Finish   Sandstone Fabric   Walnut Finish   White  White  Dot  \
0            0                  0               0      0           0   
1            0                  0               0      0           0   
2            0                  0               1      0           0   
3            0                  0               0      0           0   
4            0                  0               0      0           0   

   White  Plus  White  Show  White  Spot  
0            0            0            0  
1            0            0            0  
2            0            0            0  
3            0            0            0  
4            0            0            0

In [20]:
encoded_reviews = pd.DataFrame(alexa_countvectorizer.toarray())
encoded_reviews.head()

0     1     2     3     4     5     6     7     8     9     ...  4034  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   4035  4036  4037  4038  4039  4040  4041  4042  4043  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     1     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 4044 columns]

In [21]:
df = pd.concat([df, encoded_reviews], axis=1)
df.head()

feedback  Black  Dot  Black  Plus  Black  Show  Black  Spot  \
0         1           0            0            0            0   
1         1           0            0            0            0   
2         1           0            0            0            0   
3         1           0            0            0            0   
4         1           0            0            0            0   

   Charcoal Fabric   Configuration: Fire TV Stick  Heather Gray Fabric   \
0                 1                             0                     0   
1                 1                             0                     0   
2                 0                             0                     0   
3                 1                             0                     0   
4                 1                             0                     0   

   Oak Finish   Sandstone Fabric   ...  4034  4035  4036  4037  4038  4039  \
0            0                  0  ...     0     0     0     0     0     0   
1            0                  0  ...     0     0     0     0     0     0   
2            0                  0  ...     0     0     0     0     0     0   
3            0                  0  ...     0     1     0     0     0     0   
4            0                  0  ...     0     0     0     0     0     0   

   4040  4041  4042  4043  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 4060 columns]

<a id='3'></a><center> <h1 style="background-color:orange; color:white" ><br>Model Tuning and Result<br></h1>

In [22]:
X = df.drop(['feedback'], axis=1)
y = df['feedback']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state = 345)

print("X_train Size :",X_train.shape)
print("X_test Size :",X_test.shape)
print("y_train Size :",y_train.shape)
print("y_test Size :",y_test.shape)

X_train Size : (2362, 4059)
X_test Size : (788, 4059)
y_train Size : (2362,)
y_test Size : (788,)


In [23]:
rf_params = {"n_estimators" :[100,200,500,1000], 
             "max_features": [3,5,7], 
             "min_samples_split": [2,5,10,30],
             "max_depth": [3,5,8,None]}

rf_model = RandomForestClassifier(random_state = 357)

rf_cv_model = GridSearchCV(rf_model, rf_params, n_jobs = -1,verbose = 1).fit(X_train, y_train)

rf_tuned = RandomForestClassifier(**rf_cv_model.best_params_).fit(X,y)

Fitting 5 folds for each of 192 candidates, totalling 960 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   35.6s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-1)]: Done 446 tasks      | elapsed:  5.9min
[Parallel(n_jobs=-1)]: Done 796 tasks      | elapsed: 13.5min
[Parallel(n_jobs=-1)]: Done 960 out of 960 | elapsed: 22.1min finished


In [24]:
tuned = [rf_tuned]
print("Best Model Parameters and Scores:")
for i in tuned:
    score = cross_val_score(i, X_train, y_train, cv = 10).mean()
    print(i,"score:",score)

Best Model Parameters and Scores:
RandomForestClassifier(max_features=7, n_estimators=1000) score: 0.9309894157190876
